<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>ob</string>
		<string>ob07</string>
	</array>
	<key>keyEquivalent</key>
	<string>^~@o</string>
	<key>name</key>
	<string>Oberon</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>match</key>
			<string>\b(FOR|REPEAT|IF|ELSIF|UNTIL|WHILE|DO|ELSE|THEN|CASE|BY|RETURN|TO)\b</string>
			<key>name</key>
			<string>keyword.control.oberon</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(IS|DIV|MOD|OR|IN)\b</string>
			<key>name</key>
			<string>keyword.operator.oberon</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(IMPORT|BEGIN|TYPE|CONST|MODULE|VAR|PROCEDURE|END)\b</string>
			<key>name</key>
			<string>keyword.other.oberon</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(POINTER|RECORD|ARRAY|OF)\b</string>
			<key>name</key>
			<string>storage.type.oberon</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(FALSE|NIL|TRUE)\b</string>
			<key>name</key>
			<string>constant.language.oberon</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(ABS|ASR|CHR|FLT|INC|LSL|NEW|ROR|ASSERT|DEC|EXCL|FLOOR|INCL|LEN|ODD|ORD|PACK|UNPK)\b</string>
			<key>name</key>
			<string>support.function.oberon</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(CHAR|REAL|BYTE|INTEGER|SET|BOOLEAN)\b</string>
			<key>name</key>
			<string>support.type.oberon</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(([0-9][0-9A-F]*[H])|([0-9]+[.][0-9]*([ED][+-]?[0-9]+)?)|([0-9]+))\b</string>
			<key>name</key>
			<string>constant.numeric.oberon</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>"</string>
			<key>beginCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.string.begin.oberon</string>
				</dict>
			</dict>
			<key>end</key>
			<string>"</string>
			<key>endCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.string.end.oberon</string>
				</dict>
			</dict>
			<key>name</key>
			<string>string.quoted</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>\\([ntrf\\'"]|([0-7]{3}))</string>
					<key>name</key>
					<string>constant.character.escape.oberon</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>match</key>
			<string>\b([0-9][0-9A-F]+[X])\b</string>
			<key>name</key>
			<string>string.other.oberon</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>\(\*</string>
			<key>captures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.comment.oberon</string>
				</dict>
			</dict>
			<key>end</key>
			<string>\*\)</string>
			<key>name</key>
			<string>comment.block.oberon</string>
		</dict>
	</array>
	<key>scopeName</key>
	<string>source.oberon</string>
	<key>uuid</key>
	<string>81362E6A-0A64-42AD-9C72-E39330258444</string>
</dict>
</plist>
