<rtl code>
var m = function (){
var ch = 0;
var i = 0;
var b = false;
var r = 0;
var s = 0;
var a = RTL$.makeArray(10, 0);
i = 65;
ch = i;
i = (ch + i | 0) / 2 | 0;
RTL$.assert(i == 65);
a[(i - 64 | 0) * 3 | 0] = i;
i = i + (i - 1 | 0) | 0;
i = (i - i | 0) + 1 | 0;
i = (i * i | 0) + 1 | 0;
i = i * (i + 1 | 0) | 0;
i = (i / 2 | 0) + 1 | 0;
i = i / (2 + 1 | 0) | 0;
r = r / 2 + 1;
r = r / (2 + 1);
i = i % 2 + 1 | 0;
i = i % (2 + 1 | 0);
b = b && b || b;
b = b && (b || b);
b = b && b || b;
b = b || b && b;
b = b == b || b;
b = b == (b || b);
b = b != b || b;
b = b != (b || b);
s = (s | s) & ~s;
s = s | s & ~s;
s = s & s ^ s;
s = s & (s ^ s);
s = s & s | s;
s = s & (s | s);
i = (-(i * 2 | 0) | 0) + i | 0;
i = -(i * (2 + i | 0) | 0) | 0;
i = -(i % (2 * i | 0)) | 0;
i = (-i | 0) + (2 * i | 0) | 0;
s = ~s & ~~s;
}();
